### ISSUE TITLE
Resulting pom.xml contains excessive line breaks

### ISSUE THREAD

**Issue by ozimakov** [intellectivelab/unity7-maven-archetype#2] opened 2020-07-08 20:57 UTC
1. Create a new project using the archetype.
2. Take a look on the parent pom.xml. It contains a lot of unnecessary line breaks.

**Comment by ozimakov** [comment] 2020-07-08 20:58
Example:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">


    <modelVersion>4.0.0</modelVersion>


    <groupId>com.intellective.sample</groupId>


    <artifactId>u7-crm-app</artifactId>


    <version>1.0.0-SNAPSHOT</version>


    <name>Custom Unity 7 application</name>
...
```

**Comment by esmirnov-intellective** [comment] 2020-07-23 13:16
@ozimakov - Not reproduced at my Win10 laptop. Neither with locally built archetype nor with archetype from repo.maven.apache.org:

![image](https://user-images.githubusercontent.com/65232878/88290711-daee5280-ccff-11ea-9d63-1c47a552f9a1.png)

**Comment by ozimakov** [comment] 2020-08-03 18:13
@esmirnov-intellective I reproduce the issue on Windows as well.
I execute the exact command we have in the README, i.e.
`
mvn archetype:generate "-DarchetypeGroupId=com.intellective.archetypes" ^
                       "-DarchetypeArtifactId=unity7-maven-archetype" ^
                       "-DarchetypeVersion=1.0.3" ^
                       "-DgroupId=com.intellective.sample" ^
                       "-DartifactId=unity7-custom-app" ^
                       "-Dversion=1.0.0-SNAPSHOT" ^
                       "-DunityVersion=7.7.0-RC11"
`

**Comment by ozimakov** [comment] 2020-08-03 18:16
Interesting. I tried it on Linux (Ubuntu running on WSL) and it's fine.

**Comment by mimaev-intellective** [comment] 2020-10-19 06:51
Reproduce the issue on Windows with command
![image](https://user-images.githubusercontent.com/70009911/96411017-406bb580-1201-11eb-95fb-eaf6f804027a.png)

Parent pom.xml generated normally.
![image](https://user-images.githubusercontent.com/70009911/96411167-790b8f00-1201-11eb-83b1-276f55ee2792.png)

**Comment by ozimakov-intellective** [comment] 2020-10-19 08:23
Seems to be a very local problem. Closing the issue.

**Closed by ozimakov-intellective** 2020-10-19 08:23 UTC
